version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
